name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: BuildX Install
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        docker build \
        --platform linux/amd64,linux/arm64 \
        --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
        --tag ghcr.io/${{ github.repository }}:latest \
        --output "type=image,push=true" \
        .
